"""Build the final Markdown audit report from LLM sections and parsed data."""

from __future__ import annotations

from collections import Counter
from datetime import datetime


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _severity_stats(vulnerabilities: list[dict]) -> str:
    """Return a short Markdown block summarising severity distribution."""
    counts: Counter[str] = Counter(
        item.get("severity", "unknown") for item in vulnerabilities
    )
    critical = counts.get("critical", 0)
    high = counts.get("high", 0)
    total = critical + high
    lines = [
        f"| **Total High + Critical** | **{total}** |",
        f"| Critical | {critical} |",
        f"| High | {high} |",
    ]
    return "| Metric | Count |\n|---|---:|\n" + "\n".join(lines)


def build_technical_risk_table(vulnerabilities: list[dict]) -> str:
    """Render a Markdown table of all filtered vulnerabilities."""
    header = (
        "| # | Severity | ID | Vulnerability | Asset | CVSS | CVE | Remediation |\n"
        "|---:|---|---|---|---|---:|---|---|"
    )
    rows: list[str] = []
    for idx, item in enumerate(vulnerabilities, 1):
        cvss = item.get("cvss_score")
        rows.append(
            "| {idx} | {sev} | {vid} | {title} | {asset} | {cvss} | {cve} | {rem} |".format(
                idx=idx,
                sev=item.get("severity", "").upper(),
                vid=item.get("vulnerability_id", ""),
                title=item.get("title", "").replace("|", "\\|"),
                asset=item.get("affected_asset", "").replace("|", "\\|"),
                cvss=f"{cvss:.1f}" if cvss is not None else "N/A",
                cve=item.get("cve") or "N/A",
                rem=item.get("remediation", "").replace("|", "\\|")[:120],
            )
        )
    return "\n".join([header, *rows])


# ---------------------------------------------------------------------------
# Main builder
# ---------------------------------------------------------------------------
def build_report_markdown(
    org_context: str,
    vulnerabilities: list[dict],
    executive_summary: str,
    technical_analysis: str,
    detailed_findings: str,
) -> str:
    """Assemble all sections into the final Markdown report string."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    risk_table = build_technical_risk_table(vulnerabilities)
    stats = _severity_stats(vulnerabilities)

    return f"""
# ReportX – AI Audit Report

> **Generated:** {timestamp}
> **Organization Context:** {org_context}
> **Mode:** Fully Offline (Ollama local inference)

---

## Table of Contents

1. [Summary Statistics](#summary-statistics)
2. [Executive Summary](#executive-summary)
3. [Technical Risk Table](#technical-risk-table)
4. [Technical Risk Analysis & Recommendations](#technical-risk-analysis--recommendations)
5. [Detailed Findings with Remediation](#detailed-findings-with-remediation)

---

## Summary Statistics

{stats}

---

## Executive Summary

{executive_summary}

---

## Technical Risk Table

{risk_table}

---

## Technical Risk Analysis & Recommendations

{technical_analysis}

---

## Detailed Findings with Remediation

{detailed_findings}

---

*Report generated by ReportX – Offline AI Audit Engine. All analysis is
based exclusively on parsed scan evidence; no external data sources were
consulted.*
""".strip() + "\n"
